import { validateRepositoryProcessingKey } from "../storage-key";

describe("repository file-processor S3 key allowlist", () => {
  it("accepts the UUID namespace generated by generateUploadUrl", () => {
    expect(
      validateRepositoryProcessingKey(
        "repositories/7/11111111-2222-4333-8444-555555555555/policy.pdf"
      )
    ).toBe(true);
  });

  it("keeps the constrained legacy user upload namespace", () => {
    expect(validateRepositoryProcessingKey("3/1721590000000-policy.pdf")).toBe(
      true
    );
  });

  it.each([
    "repositories/7/not-a-uuid/policy.pdf",
    "repositories/7/11111111-2222-4333-8444-555555555555/nested/policy.pdf",
    "repositories/7/11111111-2222-4333-8444-555555555555/../secret.pdf",
    "/repositories/7/11111111-2222-4333-8444-555555555555/policy.pdf",
  ])("rejects unsafe or non-generated key %s", (key) => {
    expect(validateRepositoryProcessingKey(key)).toBe(false);
  });
});
