#!/usr/bin/env python3
"""psd-last30days: gather what people said about a topic across social/community
sources in the last N days and return a cited digest — Markdown for chat,
optionally a self-contained HTML artifact uploaded to S3.
"""

import argparse
import html as html_lib
import json
import re
import sys
import uuid
from urllib.parse import quote

from sources import SOURCES, SourceError

_EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


def _fail(message, code, status_code=1):
    print(json.dumps({"status": "error", "error": code, "message": message}))
    sys.exit(status_code)


def _valid_email(email):
    return bool(email) and "/" not in email and bool(_EMAIL_RE.match(email))


def build_markdown(topic, days, grouped, sources_failed):
    lines = [f"# Last {days} Days: {topic}", ""]
    if not grouped:
        lines.append("_No results found in the selected window and sources._")
    for source in sorted(grouped):
        items = grouped[source]
        lines.append(f"## {source.capitalize()} ({len(items)})")
        lines.append("")
        for it in items:
            date = it["published"][:10] if it["published"] else "undated"
            snippet = f" — {it['snippet']}" if it["snippet"] else ""
            lines.append(f"- [{it['title']}]({it['url']}) ({date}){snippet}")
        lines.append("")
    if sources_failed:
        failed_str = ", ".join(f"{f['source']} ({f['error']})" for f in sources_failed)
        lines.append(f"_Sources that failed to respond: {failed_str}_")
    return "\n".join(lines).strip() + "\n"


def build_html(topic, days, grouped, sources_failed):
    def esc(s):
        return html_lib.escape(s or "", quote=True)

    def render_item(it):
        date = esc(it["published"][:10] if it["published"] else "undated")
        snippet_html = f'<p>{esc(it["snippet"])}</p>' if it["snippet"] else ""
        return (
            f'<li><a href="{esc(it["url"])}" rel="noopener noreferrer">{esc(it["title"])}</a>'
            f'<span class="meta">{date}</span>{snippet_html}</li>'
        )

    sections = []
    for source in sorted(grouped):
        rows = "\n".join(render_item(it) for it in grouped[source])
        sections.append(
            f"<section><h2>{esc(source.capitalize())} ({len(grouped[source])})</h2><ul>{rows}</ul></section>"
        )

    failed_note = ""
    if sources_failed:
        failed_str = ", ".join(f"{esc(f['source'])} ({esc(f['error'])})" for f in sources_failed)
        failed_note = f'<p class="failed">Sources that failed to respond: {failed_str}</p>'

    body = "".join(sections) if sections else "<p>No results found in the selected window and sources.</p>"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Last {days} Days: {esc(topic)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 860px; margin: 2.5rem auto; padding: 0 1.5rem; line-height: 1.5; }}
  h1 {{ font-size: 1.6rem; }}
  h2 {{ font-size: 1.15rem; margin-top: 2rem; border-bottom: 1px solid #8883; padding-bottom: .3rem; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ margin: .9rem 0; }}
  a {{ font-weight: 600; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .meta {{ display: block; font-size: .8rem; opacity: .65; margin-top: .1rem; }}
  p {{ margin: .3rem 0 0; opacity: .85; }}
  .failed {{ margin-top: 2.5rem; font-size: .85rem; opacity: .6; }}
  footer {{ margin-top: 3rem; font-size: .75rem; opacity: .5; }}
</style>
</head>
<body>
<h1>Last {days} Days: {esc(topic)}</h1>
{body}
{failed_note}
<footer>Generated by psd-last30days — Peninsula School District AI Studio agent.</footer>
</body>
</html>
"""


def upload_html(html_body, user_email):
    import os

    import boto3

    bucket = os.environ.get("WORKSPACE_BUCKET")
    if not bucket:
        _fail("WORKSPACE_BUCKET env var not set — cannot upload HTML artifact", "misconfigured")
    region = os.environ.get("AWS_REGION", "us-east-1")
    key = f"public-images/{user_email}/{uuid.uuid4()}.html"
    s3 = boto3.client("s3", region_name=region)
    s3.put_object(
        Bucket=bucket,
        Key=key,
        Body=html_body.encode("utf-8"),
        ContentType="text/html; charset=utf-8",
        Metadata={"generated_by": "psd-last30days"},
    )
    encoded_key = "/".join(quote(seg) for seg in key.split("/"))
    return f"https://{bucket}.s3.{region}.amazonaws.com/{encoded_key}"


def main():
    parser = argparse.ArgumentParser(description="Research what was said about a topic in the last N days.")
    parser.add_argument("--topic", required=True)
    parser.add_argument("--user", required=True)
    parser.add_argument("--days", type=int, default=30)
    parser.add_argument("--format", choices=["md", "html", "both"], default="md")
    parser.add_argument("--sources", default=",".join(SOURCES.keys()))
    parser.add_argument("--limit-per-source", type=int, default=10, dest="limit")
    args = parser.parse_args()

    if not args.topic.strip():
        _fail("`--topic` must not be empty", "bad_args")
    if len(args.topic) > 200:
        _fail("`--topic` must be 200 characters or fewer", "bad_args")
    if not _valid_email(args.user):
        _fail("`--user` must be a valid email address", "bad_args")
    if args.days < 1 or args.days > 90:
        _fail("`--days` must be between 1 and 90", "bad_args")
    if args.limit < 1 or args.limit > 50:
        _fail("`--limit-per-source` must be between 1 and 50", "bad_args")

    requested = [s.strip() for s in args.sources.split(",") if s.strip()]
    unknown = [s for s in requested if s not in SOURCES]
    if unknown:
        _fail(f"Unknown source(s): {', '.join(unknown)}. Valid: {', '.join(SOURCES)}", "bad_args")

    grouped = {}
    sources_failed = []
    for name in requested:
        try:
            items = SOURCES[name](args.topic, args.days, args.limit)
        except SourceError as exc:
            sources_failed.append({"source": name, "error": str(exc)})
            continue
        except Exception as exc:  # noqa: BLE001 — an external API's malformed response must not crash the whole run
            sources_failed.append({"source": name, "error": f"parse_error: {exc}"})
            continue
        if items:
            grouped[name] = items

    item_count = sum(len(v) for v in grouped.values())
    if item_count == 0 and requested and len(sources_failed) == len(requested):
        _fail(
            f"All {len(requested)} source(s) failed: "
            + "; ".join(f"{f['source']}: {f['error']}" for f in sources_failed),
            "upstream_error",
        )

    markdown = build_markdown(args.topic, args.days, grouped, sources_failed)

    result = {
        "status": "ok",
        "topic": args.topic,
        "window_days": args.days,
        "sources_used": sorted(grouped.keys()),
        "sources_failed": sources_failed,
        "item_count": item_count,
        "markdown": markdown,
    }

    if args.format in ("html", "both"):
        html_body = build_html(args.topic, args.days, grouped, sources_failed)
        result["html_url"] = upload_html(html_body, args.user)

    print(json.dumps(result))


if __name__ == "__main__":
    main()
