#!/usr/bin/env npx tsx
/**
 * Drizzle Migration Preparation Script
 *
 * Prepares drizzle-kit generated migrations for the Lambda-based migration system.
 * This script:
 * 1. Finds the latest drizzle-generated migration
 * 2. Validates SQL for Lambda/RDS Data API compatibility
 * 3. Renames to project convention (NNN-description.sql)
 * 4. Adds documentation header
 * 5. Copies to Lambda schema directory
 * 6. Reminds developer to update MIGRATION_FILES array
 *
 * Part of Epic #526 - RDS Data API to Drizzle ORM Migration
 * Issue #539 - Integrate Drizzle-Kit with existing Lambda migration system
 *
 * Usage:
 *   npx tsx scripts/drizzle-helpers/prepare-migration.ts "add-user-preferences"
 *   npm run migration:prepare -- "add-user-preferences"
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  getAbsolutePath,
  getNextMigrationNumber,
  sanitizeForFilename,
  validateNotEmpty,
} from "./lib/migration-utils";

// Constants
const DRIZZLE_MIGRATIONS_DIR = "./drizzle/migrations";
const LAMBDA_SCHEMA_DIR = "./infra/database/schema";

// RDS Data API incompatible patterns
const INCOMPATIBLE_PATTERNS = [
  {
    pattern: /\bconcurrently\b/gi,
    message:
      "CONCURRENTLY operations are incompatible with RDS Data API (requires autocommit mode)",
    fix: "Use 'CREATE INDEX IF NOT EXISTS' instead of 'CREATE INDEX CONCURRENTLY'",
  },
  {
    pattern: /\bdo\s+\$\$/gi,
    message:
      "Dollar-quoted DO blocks are incompatible with RDS Data API statement splitter",
    fix: "Use CREATE OR REPLACE FUNCTION with single-quoted body instead",
  },
  {
    pattern: /\b(begin|commit|rollback)\s*;/gi,
    message:
      "Transaction control statements are incompatible - Lambda manages transactions",
    fix: "Remove BEGIN/COMMIT/ROLLBACK statements, Lambda wraps migrations in transactions",
  },
];

interface ValidationError {
  line: number;
  statement: string;
  message: string;
  fix: string;
}


/**
 * Validate SQL for RDS Data API compatibility
 * Fixed: Use matchAll() to avoid infinite loop with global regex
 */
function validateSQL(sql: string): ValidationError[] {
  const errors: ValidationError[] = [];
  const lines = sql.split("\n");

  // Remove comments before checking (but preserve line numbers)
  const sqlWithoutComments = lines
    .map((line) => {
      // Remove single-line comments but preserve line structure
      const commentIndex = line.indexOf("--");
      if (commentIndex >= 0) {
        return line.substring(0, commentIndex);
      }
      return line;
    })
    .join("\n");

  for (const { pattern, message, fix } of INCOMPATIBLE_PATTERNS) {
    // Use matchAll() to avoid regex state issues with global flag
    const matches = [...sqlWithoutComments.matchAll(pattern)];

    for (const match of matches) {
      // Find line number
      const beforeMatch = sqlWithoutComments.substring(0, match.index!);
      const lineNumber = (beforeMatch.match(/\n/g) || []).length + 1;

      errors.push({
        line: lineNumber,
        statement: match[0],
        message,
        fix,
      });
    }
  }

  return errors;
}

/**
 * Add documentation header to migration file
 */
function addMigrationHeader(
  sql: string,
  migrationNumber: number,
  description: string
): string {
  const now = new Date().toISOString();
  const formattedNumber = String(migrationNumber).padStart(3, "0");

  const header = `-- Migration ${formattedNumber}: ${description}
-- Generated by drizzle-kit on ${now.split("T")[0]}
-- Part of Epic #526 - RDS Data API to Drizzle ORM Migration
--
-- This migration was generated from Drizzle schema changes.
-- Review the SQL before deployment to ensure Lambda/RDS Data API compatibility.
--
-- COMPATIBILITY NOTES:
-- - NO CONCURRENTLY (not supported by RDS Data API)
-- - Use IF NOT EXISTS/IF EXISTS for idempotency
-- - Single-statement execution (semicolon-separated)
--
-- ROLLBACK: See end of file for rollback SQL

`;

  return header + sql;
}

/**
 * Find the most recent drizzle-generated migration
 */
function findLatestDrizzleMigration(): string | null {
  if (!fs.existsSync(DRIZZLE_MIGRATIONS_DIR)) {
    return null;
  }

  const files = fs.readdirSync(DRIZZLE_MIGRATIONS_DIR);
  const sqlFiles = files.filter(
    (f) => f.endsWith(".sql") && !f.startsWith(".")
  );

  if (sqlFiles.length === 0) {
    return null;
  }

  // Sort by modification time (most recent first)
  const sortedFiles = sqlFiles
    .map((f) => ({
      name: f,
      mtime: fs.statSync(path.join(DRIZZLE_MIGRATIONS_DIR, f)).mtime,
    }))
    .sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

  return sortedFiles[0].name;
}


/**
 * Main execution
 */
function main(): void {
  const description = process.argv[2];

  if (!description) {
    console.error("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.error("❌ Missing migration description");
    console.error("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.error("");
    console.error("Usage: npx tsx scripts/drizzle-helpers/prepare-migration.ts <description>");
    console.error("Example: npx tsx scripts/drizzle-helpers/prepare-migration.ts 'add-user-preferences'");
    console.error("");
    process.exit(1);
  }

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("🔧 Drizzle Migration Preparation");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("");

  // Step 1: Find latest drizzle migration
  console.log("📂 Step 1: Finding latest drizzle-generated migration...");
  const latestMigration = findLatestDrizzleMigration();

  if (!latestMigration) {
    console.error("");
    console.error("❌ No drizzle-generated migrations found in", DRIZZLE_MIGRATIONS_DIR);
    console.error("");
    console.error("Run 'npm run drizzle:generate' first to generate migrations from schema changes.");
    console.error("");
    process.exit(1);
  }

  console.log(`   Found: ${latestMigration}`);

  // Step 2: Read and validate SQL
  console.log("");
  console.log("🔍 Step 2: Validating SQL for RDS Data API compatibility...");

  const sourcePath = getAbsolutePath(path.join(DRIZZLE_MIGRATIONS_DIR, latestMigration));
  const sql = fs.readFileSync(sourcePath, "utf-8");

  // Validate SQL is not empty
  try {
    validateNotEmpty(sql);
  } catch (error) {
    console.error("");
    console.error("❌", (error as Error).message);
    console.error("");
    console.error(`File: ${sourcePath}`);
    console.error("");
    process.exit(1);
  }

  const errors = validateSQL(sql);

  if (errors.length > 0) {
    console.error("");
    console.error("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.error("❌ SQL VALIDATION FAILED - Incompatible patterns detected");
    console.error("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.error("");

    for (const error of errors) {
      console.error(`Line ${error.line}: ${error.statement}`);
      console.error(`  Problem: ${error.message}`);
      console.error(`  Fix: ${error.fix}`);
      console.error("");
    }

    console.error("Please fix these issues in the drizzle-generated SQL before proceeding.");
    console.error(`File: ${sourcePath}`);
    console.error("");
    process.exit(1);
  }

  console.log("   ✅ SQL is Lambda/RDS Data API compatible");

  // Step 3: Get next migration number
  console.log("");
  console.log("🔢 Step 3: Determining next migration number...");

  const nextNumber = getNextMigrationNumber();
  const formattedNumber = String(nextNumber).padStart(3, "0");
  const sanitizedDesc = sanitizeForFilename(description);
  const newFilename = `${formattedNumber}-${sanitizedDesc}.sql`;

  console.log(`   Next number: ${formattedNumber}`);
  console.log(`   New filename: ${newFilename}`);

  // Step 4: Add header and prepare content
  console.log("");
  console.log("📝 Step 4: Adding migration header...");

  const preparedSQL = addMigrationHeader(sql, nextNumber, description);

  // Step 5: Copy to Lambda schema directory
  console.log("");
  console.log("📋 Step 5: Copying to Lambda schema directory...");

  const destPath = getAbsolutePath(path.join(LAMBDA_SCHEMA_DIR, newFilename));
  fs.writeFileSync(destPath, preparedSQL);

  console.log(`   ✅ Created: ${destPath}`);

  // Step 6: Show next steps
  console.log("");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("✅ Migration Prepared Successfully!");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("");
  console.log("⚠️  NEXT STEPS (manual):");
  console.log("");
  console.log(`1. Review the migration SQL at: ${destPath}`);
  console.log("");
  console.log(`2. Add to MIGRATION_FILES array in ./infra/database/lambda/db-init-handler.ts:`);
  console.log("");
  console.log(`   const MIGRATION_FILES = [`);
  console.log(`     // ... existing migrations ...`);
  console.log(`     '${newFilename}',  // ← ADD THIS LINE`);
  console.log(`   ];`);
  console.log("");
  console.log(`3. Update the Drizzle schema export if you added new tables:`);
  console.log(`   - Add export to lib/db/schema/index.ts`);
  console.log("");
  console.log(`4. Test the migration:`);
  console.log(`   cd infra && npx cdk deploy AIStudio-DatabaseStack-Dev`);
  console.log("");
  console.log(`5. Verify in migration_log table that it ran successfully`);
  console.log("");
}

try {
  main();
} catch (error) {
  console.error("Fatal error:", error);
  process.exit(1);
}
